// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

// Load .env.local explicitly
dotenv.config({ path: path.resolve(__dirname, ".env.local") });

const databaseUrl = process.env.DATABASE_URL || "postgresql://neondb_owner:npg_dkHeNiz7sIp2@ep-summer-butterfly-ayjykmfc-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
